INSERT INTO `part` VALUES
(1,2,_binary '','процессор'),
(2,3,_binary '','материнская плата'),
(3,2,_binary '\0','звуковая карта'),
(4,4,_binary '\0','подсветка корпуса'),
(5,1,_binary '\0','HDD диск'),
(6,10,_binary '','корпус'),
(7,10,_binary '','память'),
(8,15,_binary '','SSD диск'),
(9,10,_binary '\0','видеокарта'),
(10,12,_binary '\0','Картридер'),
(11,4,_binary '\0','TV-карта'),
(12,5,_binary '','Сетевой контроллер'),
(13,6,_binary '\0','Спутниковая карта'),
(14,9,_binary '','оптический привод'),
(15,7,_binary '\0','карман для диска'),
(16,6,_binary '','Процессор Intel Core i3'),
(17,9,_binary '','Процессор Intel Core i5'),
(18,8,_binary '','Процессор Intel Core i7'),
(19,5,_binary '','Корпус QUBE Armor Black '),
(20,20,_binary '','Корпус NZXT S340 Elite Black-Red'),
(21,9,_binary '','Корпус DeepCool QuadStellar');
